[package]
name = "rust-clap-output-formats"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4", features = ["derive", "env", "wrap_help"]}
comfy-table = "6.1.4"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
serde_yaml = "0.9"

